### ISSUE TITLE
关于模型的两个输出

### ISSUE THREAD

**Issue by flyleeee** [zbh2047/L_inf-dist-net-v2#1]
请问return x * self.scalar, margin / (2 * eps)中的后者是什么

**Comment by zbh2047** [comment]
你好！你可以看下论文里的loss，前者用于cross entropy loss，后者用于clipped hinge loss，除以2 eps这里的2eps=theta对应hinge threshold超参

**Comment by flyleeee** [comment]
这里的margin的计算过程是怎样的呢，没有看太懂。。因为我看他还能直接作为worst_outputs，又可以当作margin。。
